name: Deployment C++ Studio

on:
  workflow_dispatch:

jobs:
  deploy-mac:
    runs-on: macos-12

    steps:
      - name: Checkout source code repo
        uses: actions/checkout@v2.4.2
        with:
          repository: muselive-inc/museLIVEStudio
          ref: main
          token: ${{ secrets.GH_TOKEN }}
  
      - name: Install Qt
        uses: jurplel/install-qt-action@v3.0.0
        with:
          version: 6.4.0
    
      - name: Check Installation
        run: |
          echo ${{env.Qt6_DIR}}
  
      - name: Install Dependencies
        run: |
          brew install openssl@1.1 ffmpeg
      
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -S .. -B . -D CMAKE_GENERATOR:STRING=Ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_PREFIX_PATH:PATH=${{env.Qt6_DIR}}/macos -DOPENSSL_ROOT_DIR:STRING=/opt/homebrew/opt/openssl@3 -DFFMPEG_ROOT_DIR:STRING=/opt/homebrew/opt/ffmpeg
      
      - name: Download FFMPEG Binary
        run: |
          python3 scripts/download_ffmpeg.py
          chmod +x stream_process/ffmpeg
      
      - name: "Import Certificate: Developer ID"
        uses: devbotsxyz/import-signing-certificate@v1.0.0
        with:
          certificate-data: ${{ secrets.CERTIFICATES_P12 }}
          certificate-passphrase: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
          keychain-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
  
      - name: Build Artifacts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PW: ${{ secrets.APPLE_ID_PW }}
        run: |
          yarn build:back
          yarn build:front
          yarn release
      
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: python3 scripts/upload.py

