name: Streaming Test

on:
  workflow_dispatch:

jobs:
  perform-test:
    runs-on: macos-12

    steps:
      - name: Checkout source code repo
        uses: actions/checkout@v2.4.2
        with:
          repository: muselive-inc/museLIVEStudio
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
  
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          brew install ffmpeg
          pip3 install -r test/requirements.txt

      - name: Setup Cpp (C++ / C)
        uses: aminya/setup-cpp@v0.24.1
        with:
          ninja: 1.10.2
      
      - name: Build Test Script
        run: |
          cd test
          mkdir build
          cd build
          FFMPEG_ROOT_DIR=$(brew --prefix ffmpeg)
          cmake .. -G Ninja -DFFMPEG_ROOT_DIR=${FFMPEG_ROOT_DIR}
          ninja
      
      - name: Run Test
        run: |
          cd test
          python3 run.py ${{ secrets.APPLE_ID }} ${{ secrets.MUSE_PASSCODE }}
