name: Big Sur x86_64

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release_test:
    runs-on: macos-11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4.4.0

      - name: Download release file and run
        run: |
          python3 get_studio.py
          sudo hdiutil attach studio.dmg
          /Volumes/museLIVEStudio/museLIVEStudio.app/Contents/MacOS/museLIVEStudio test
          sudo hdiutil detach /Volumes/museLIVEStudio
